export const defaultSEO = {
  title: 'Krishna Naik | Krishna — Full Stack Developer & AI/ML Engineer Portfolio',
  description:
    'Official portfolio of Krishna Naik (Krishna Umesh Naik, Krishna) — Full-Stack Developer, Software Engineer & AI/ML Specialist based in Bengaluru. Explore Krishna Naik projects, skills, education, and GitHub intelligence.',
  url: 'https://krishna-naik.vercel.app',
  siteName: 'Krishna Naik Portfolio',
  author: 'Krishna Naik (Krishna Umesh Naik)',
  twitterHandle: '@KrishnaNaik',
};

export const seoKeywords = [
  // Primary Exact Match Variations (All Cases)
  'Krishna',
  'krishna',
  'KRISHNA',
  'Krishna Naik',
  'krishna naik',
  'KRISHNA NAIK',
  'Krishna Umesh Naik',
  'krishna umesh naik',
  'KRISHNA UMESH NAIK',
  'Krishna U Naik',
  'krishna u naik',
  'KRISHNA U NAIK',
  'Krishna U. Naik',
  'krishna u. naik',
  'KrishnaNaik',
  'krishnanaik',
  'KRISHNANAIK',
  'KrishnaNaik6',
  'krishnanaik6',
  'KRISHNANAIK6',
  'Krishna_Naik',
  'krishna_naik',
  'krishna-naik',
  'krishna.naik',
  'krishna-umesh-naik',
  'krishna_umesh_naik',

  // Portfolio & Identity Queries (All Cases)
  'Krishna Naik portfolio',
  'krishna naik portfolio',
  'KRISHNA NAIK PORTFOLIO',
  'Krishna portfolio',
  'krishna portfolio',
  'KRISHNA PORTFOLIO',
  'Krishna Umesh Naik portfolio',
  'krishna umesh naik portfolio',
  'KRISHNA UMESH NAIK PORTFOLIO',
  'Krishna website',
  'krishna website',
  'KRISHNA WEBSITE',
  'Krishna Naik website',
  'krishna naik website',
  'KRISHNA NAIK WEBSITE',
  'Krishna Naik official website',
  'krishna naik official website',
  'Krishna Naik official portfolio',
  'krishna naik official portfolio',
  'Krishna Naik personal website',
  'krishna naik personal website',
  'Krishna Naik developer portfolio',
  'krishna naik developer portfolio',
  'Portfolio of Krishna Naik',
  'portfolio of krishna naik',
  'Portfolio of Krishna',
  'portfolio of krishna',
  'krishna-naik.vercel.app',
  'krishna vercel',
  'krishna naik vercel',

  // Roles & Professions (All Cases)
  'Krishna Naik developer',
  'krishna naik developer',
  'KRISHNA NAIK DEVELOPER',
  'Krishna developer',
  'krishna developer',
  'KRISHNA DEVELOPER',
  'Krishna Naik software developer',
  'krishna naik software developer',
  'KRISHNA NAIK SOFTWARE DEVELOPER',
  'Krishna software developer',
  'krishna software developer',
  'KRISHNA SOFTWARE DEVELOPER',
  'Krishna Naik software engineer',
  'krishna naik software engineer',
  'KRISHNA NAIK SOFTWARE ENGINEER',
  'Krishna software engineer',
  'krishna software engineer',
  'KRISHNA SOFTWARE ENGINEER',
  'Krishna Naik full stack developer',
  'krishna naik full stack developer',
  'KRISHNA NAIK FULL STACK DEVELOPER',
  'Krishna full stack developer',
  'krishna full stack developer',
  'KRISHNA FULL STACK DEVELOPER',
  'Krishna Naik full stack',
  'krishna naik full stack',
  'Krishna full stack',
  'krishna full stack',
  'Krishna Naik frontend developer',
  'krishna naik frontend developer',
  'Krishna frontend developer',
  'krishna frontend developer',
  'Krishna Naik backend developer',
  'krishna naik backend developer',
  'Krishna backend developer',
  'krishna backend developer',
  'Krishna Naik AI engineer',
  'krishna naik AI engineer',
  'KRISHNA NAIK AI ENGINEER',
  'Krishna AI engineer',
  'krishna AI engineer',
  'KRISHNA AI ENGINEER',
  'Krishna AI',
  'krishna AI',
  'KRISHNA AI',
  'Krishna Naik AI',
  'krishna naik AI',
  'KRISHNA NAIK AI',
  'Krishna Naik AI ML developer',
  'krishna naik AI ML developer',
  'Krishna AI ML developer',
  'krishna AI ML developer',
  'Krishna Naik AI ML engineer',
  'krishna naik AI ML engineer',
  'Krishna Naik machine learning engineer',
  'krishna naik machine learning engineer',
  'Krishna machine learning',
  'krishna machine learning',
  'Krishna Naik web developer',
  'krishna naik web developer',
  'Krishna web developer',
  'krishna web developer',
  'Krishna Naik programmer',
  'krishna naik programmer',
  'Krishna programmer',
  'krishna programmer',
  'Krishna Naik coder',
  'krishna naik coder',
  'Krishna coder',
  'krishna coder',

  // Tech Stack & Engineering
  'Krishna Naik Next.js',
  'krishna naik next.js',
  'Krishna Naik Next.js developer',
  'krishna naik next.js developer',
  'Krishna Next.js developer',
  'Krishna Naik React',
  'krishna naik react',
  'Krishna Naik React developer',
  'krishna naik react developer',
  'Krishna React developer',
  'Krishna Naik TypeScript',
  'krishna naik typescript',
  'Krishna Naik TypeScript developer',
  'Krishna Naik JavaScript',
  'Krishna Naik Python',
  'krishna naik python',
  'Krishna Naik Python developer',
  'krishna naik python developer',
  'Krishna Python developer',
  'Krishna Naik MERN stack',
  'Krishna Naik Three.js',
  'Krishna Naik AI projects',
  'krishna naik AI projects',
  'Krishna AI projects',
  'krishna AI projects',
  'Krishna Naik ML projects',
  'Krishna Naik intelligent systems',
  'Krishna Naik computer science',

  // Social & Community Profiles
  'Krishna Naik GitHub',
  'krishna naik github',
  'KRISHNA NAIK GITHUB',
  'Krishna GitHub',
  'krishna github',
  'KRISHNA GITHUB',
  'Krishna Naik LinkedIn',
  'krishna naik linkedin',
  'KRISHNA NAIK LINKEDIN',
  'Krishna LinkedIn',
  'krishna linkedin',
  'Krishna Naik Instagram',
  'krishna naik instagram',
  'Krishna Instagram',
  'krishna instagram',
  'Krishna Naik open source',
  'Krishna Naik NEXIS',
  'Krishna Naik projects',
  'krishna naik projects',

  // Location & Education
  'Krishna Naik Bengaluru',
  'krishna naik bengaluru',
  'Krishna Bengaluru',
  'krishna bengaluru',
  'Krishna Naik Bangalore',
  'krishna naik bangalore',
  'Krishna Bangalore',
  'krishna bangalore',
  'Krishna Naik Karnataka',
  'krishna naik karnataka',
  'Krishna Naik India',
  'krishna naik india',
  'Krishna Naik Ramaiah Institute of Technology',
  'krishna naik ramaiah institute of technology',
  'Krishna Ramaiah Institute of Technology',
  'Krishna Naik Ramaiah',
  'krishna naik ramaiah',
  'Krishna Ramaiah',
  'krishna ramaiah',
  'Krishna Naik RIT',
  'krishna naik rit',
  'Krishna RIT',
  'krishna rit',
  'Krishna Naik MSRIT',
  'krishna naik msrit',
  'Krishna MSRIT',
  'krishna msrit',
  'Full Stack Developer Bengaluru',
  'AI ML Engineer Bengaluru',
  'Software Engineer Bengaluru',
  'Next.js Developer India',
  'React Developer Bengaluru',
];

export function generatePersonJSONLD() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    '@id': 'https://krishna-naik.vercel.app/#person',
    name: 'Krishna Naik',
    givenName: 'Krishna',
    familyName: 'Naik',
    additionalName: 'Umesh',
    alternateName: [
      'Krishna',
      'krishna',
      'KRISHNA',
      'Krishna Naik',
      'krishna naik',
      'KRISHNA NAIK',
      'Krishna Umesh Naik',
      'krishna umesh naik',
      'KRISHNA UMESH NAIK',
      'Krishna U Naik',
      'krishna u naik',
      'KRISHNA U NAIK',
      'Krishna U. Naik',
      'krishna u. naik',
      'KrishnaNaik',
      'krishnanaik',
      'KRISHNANAIK',
      'KrishnaNaik6',
      'krishnanaik6',
      'KRISHNANAIK6',
      'Krishna_Naik',
      'krishna_naik',
      'krishna-naik',
      'krishna.naik',
      'krishna-umesh-naik',
      'Krishna Portfolio',
      'krishna portfolio',
      'KRISHNA PORTFOLIO',
      'Krishna Naik Portfolio',
      'krishna naik portfolio',
      'KRISHNA NAIK PORTFOLIO',
      'Krishna Developer',
      'krishna developer',
      'KRISHNA DEVELOPER',
      'Krishna Naik Developer',
      'krishna naik developer',
      'KRISHNA NAIK DEVELOPER',
      'Krishna Naik Software Engineer',
      'krishna naik software engineer',
      'Krishna Naik Full Stack Developer',
      'krishna naik full stack developer',
      'Krishna Naik AI Engineer',
      'krishna naik AI engineer',
      'Krishna Naik Web Developer',
      'krishna naik web developer',
    ],
    disambiguatingDescription:
      'Krishna Naik (Krishna, Krishna Umesh Naik) is a Computer Science AI & ML student at Ramaiah Institute of Technology, Full-Stack Developer, and software engineer based in Bengaluru, India.',
    url: 'https://krishna-naik.vercel.app',
    image: 'https://krishna-naik.vercel.app/k.svg',
    jobTitle: [
      'Full Stack Developer',
      'Software Developer',
      'AI & ML Engineer',
      'Software Engineer',
      'Web Developer',
      'React Developer',
      'Next.js Developer',
      'TypeScript Developer',
      'Python Developer',
    ],
    description:
      'Krishna Naik (Krishna Umesh Naik, Krishna) is a Full-Stack Developer, AI/ML Engineer, and Software Developer based in Bengaluru, Karnataka, India specializing in Next.js, React, Python, TypeScript, and AI applications.',
    gender: 'Male',
    nationality: {
      '@type': 'Country',
      name: 'India',
    },
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Bengaluru',
      addressRegion: 'Karnataka',
      addressCountry: 'India',
    },
    alumniOf: [
      {
        '@type': 'EducationalOrganization',
        name: 'M S Ramaiah Institute Of Technology',
        alternateName: ['Ramaiah Institute of Technology', 'MSRIT', 'RIT Bengaluru'],
        url: 'https://www.msrit.edu/',
      },
      {
        '@type': 'EducationalOrganization',
        name: 'Govt. Polytechnic Siddapur',
        alternateName: ['GPT Siddapur'],
      },
    ],
    knowsAbout: [
      'Krishna Naik',
      'Full Stack Development',
      'Software Engineering',
      'Artificial Intelligence',
      'Machine Learning',
      'Deep Learning',
      'AI Projects',
      'React',
      'React 19',
      'Next.js',
      'Next.js 15',
      'TypeScript',
      'JavaScript',
      'Python',
      'MERN Stack',
      'Node.js',
      'Express.js',
      'MongoDB',
      'PostgreSQL',
      'SQL',
      'Three.js',
      'Tailwind CSS',
      'Git & GitHub',
      'Cloud & Scalable Systems',
    ],
    hasOccupation: {
      '@type': 'Occupation',
      name: 'Full-Stack Developer & AI/ML Engineer',
      occupationLocation: {
        '@type': 'City',
        name: 'Bengaluru',
      },
      skills: 'Full Stack Web Development, AI/ML Engineering, Next.js, React, Python, TypeScript',
    },
    sameAs: [
      'https://github.com/KrishnaNaik6',
      'https://www.linkedin.com/in/krishnaunaik/',
      'https://www.instagram.com/krishna_nk08/',
      'https://krishna-naik.vercel.app',
    ],
    mainEntityOfPage: 'https://krishna-naik.vercel.app',
  };
}

export function generateWebSiteJSONLD() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': 'https://krishna-naik.vercel.app/#website',
    name: 'Krishna Naik Portfolio',
    alternateName: [
      'Krishna Naik',
      'krishna naik',
      'KRISHNA NAIK',
      'Krishna',
      'krishna',
      'KRISHNA',
      'Krishna Umesh Naik',
      'krishna umesh naik',
      'KRISHNA UMESH NAIK',
      'KrishnaNaik',
      'krishnanaik',
      'KrishnaNaik6',
      'krishnanaik6',
      'Krishna Portfolio',
      'krishna portfolio',
      'KRISHNA PORTFOLIO',
      'Krishna Naik Portfolio',
      'krishna naik portfolio',
      'KRISHNA NAIK PORTFOLIO',
      'Krishna Naik (Krishna Umesh Naik) Developer Portfolio',
      'Krishna Naik Official Website',
      'Portfolio of Krishna Naik',
      'Krishna Naik Website',
      'krishna-naik.vercel.app',
    ],
    url: 'https://krishna-naik.vercel.app',
    image: 'https://krishna-naik.vercel.app/k.svg',
    description:
      'Official portfolio website of Krishna Naik (Krishna Umesh Naik, Krishna) — Full Stack Developer, Software Developer & AI/ML Engineer.',
    publisher: {
      '@id': 'https://krishna-naik.vercel.app/#person',
    },
    author: {
      '@id': 'https://krishna-naik.vercel.app/#person',
    },
    inLanguage: 'en-US',
    keywords: seoKeywords.join(', '),
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: 'https://krishna-naik.vercel.app/?q={search_term_string}',
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

export function generateProfilePageJSONLD() {
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfilePage',
    '@id': 'https://krishna-naik.vercel.app/#profilepage',
    url: 'https://krishna-naik.vercel.app',
    name: 'Krishna Naik (Krishna) — Full Stack Developer & AI/ML Engineer Profile',
    isPartOf: {
      '@id': 'https://krishna-naik.vercel.app/#website',
    },
    mainEntity: {
      '@id': 'https://krishna-naik.vercel.app/#person',
    },
    description:
      'Official developer profile and portfolio of Krishna Naik (Krishna Umesh Naik, Krishna) featuring intelligent systems, full-stack web applications, and open-source intelligence.',
    breadcrumb: {
      '@id': 'https://krishna-naik.vercel.app/#breadcrumb',
    },
  };
}

export function generateBreadcrumbJSONLD() {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    '@id': 'https://krishna-naik.vercel.app/#breadcrumb',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://krishna-naik.vercel.app',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Krishna Naik Portfolio',
        item: 'https://krishna-naik.vercel.app',
      },
    ],
  };
}

export function generateStructuredDataGraph() {
  return {
    '@context': 'https://schema.org',
    '@graph': [
      generatePersonJSONLD(),
      generateWebSiteJSONLD(),
      generateProfilePageJSONLD(),
      generateBreadcrumbJSONLD(),
    ],
  };
}
